### ISSUE TITLE
Time/key-locked scrambles?

### ISSUE THREAD

**Issue by lgarron** [cubing/tnoodle#139]
Right now, we use a single password to protect all scrambles.
Since we have to use a lot of competitors as rotating staff, this is practical, but also requires a lot of trust (e.g. not to peek at/use scrambles from the wrong rounds, whether accidentally or on purpose).

Here is an "ideal" sort of solution:
- All scrambling stations are connected to the internet with some output from TNoodle.
- The Delegate has an app that allows them to unlock some subset of the scrambles at any given moment.
- The stations can view *only those* scrambles. Ideally using some crypto, but at the very least with an interface that requires significant intent/permission to bypass.
- Ideally, some of this would be automated using a time schedule.

This is definitely not perfect, but how many of those benefits could we bring, say, to an HTML-based TNoodle output?

**Comment by jfly** [comment]
TNoodle is not going to handle this. This will be up to competition managers such as [CCM](https://github.com/cubing/ccm).
