### ISSUE TITLE
Finalize Square-1 Filtering Limit

### ISSUE THREAD

**Issue by lgarron** [cubing/tnoodle#153]
We need to know the final number for the Regulations:

https://github.com/cubing/wca-documents/issues/129
https://www.worldcubeassociation.org/regulations/2014-draft/#4b3

Also see #151.

**Comment by StachuDotNet** [comment]
Has a number yet been decided on?

**Comment by lgarron** [comment]
We've been using [11](https://www.worldcubeassociation.org/regulations/#4b3d), but the metric has been glossed over.

**Comment by lgarron** [comment]
Might as well close this, though.

**Comment by jfly** [comment]
Why is it okay to gloss over the metric? This is related to https://github.com/cubing/tnoodle/blob/c6c0f6650e10d4ae76467532deb19a2504de9b67/scrambles/src/puzzle/SquareOnePuzzle.java#L32-L34, which refers to Chen Shuang's square one solver using a different metric than we agreed upon for filtering.

**Comment by lgarron** [comment]
> okay to gloss over the metric

I didn't say it was okay. :-P
If we want to fix the metric thing, we should file a separate bug.
