### ISSUE TITLE
F in PDF scrambles could be mistaken for F'

### ISSUE THREAD

**Issue by UnsolvedCypher** [cubing/tnoodle#191]
The font used in the PDF files has a little serif hanging off of the upper-right of the F which could be mistaken for an apostrophe. I think it might be better to use a non-serif monospace font to avoid the similarity so that scramblers do not get confused.

**Comment by jfly** [comment]
Could you include a screenshot, please?

**Comment by UnsolvedCypher** [comment]
Here it is - I'm running Arch Linux. I know I'm not the only one because scrambles provided by Tim Reynolds are also in this font. I believe he uses Ubuntu.

![tnoodle-font](https://cloud.githubusercontent.com/assets/3170853/7217770/00ffe748-e612-11e4-934e-c08dd7093c2c.png)

**Comment by jfly** [comment]
Hmm... here's my font setup on my arch laptop: https://github.com/jfly/dotfiles#fonts. Have you installed any of those? That might explain why I'm seeing something different than you guys.

Either way, I'm not super knowledgeable about PDFs and fonts. I know we specify "embedded" when including the font: https://github.com/cubing/tnoodle/blob/73fe06041a982e71536abb6673f71a81ef4c35a0/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L800, which I would have hoped meant that everyone would see the same thing everywhere. Apparently thats not the case =(. I'm not super interested in learning about PDFs and embedding fonts. If you're interested in researching iTextPdf and this stuff, a PR is very welcome.

**Comment by UnsolvedCypher** [comment]
I'm not sure what the font is in your screenshot, but according to the code you linked to, Courier is the font that is supposed to be used. You can see [right here](http://www.fonts.com/font/adobe/courier) what that is supposed to look like. It looks like you do not have Courier installed; ttf-ms-fonts is the relevant AUR package.

**Comment by jfly** [comment]
Gotcha. Again, I'm honestly not super excited to dig into fonts and pdfs, and would rather focus on moving us towards html/css/javascript. This is all still a ways out, so I will leave this issue open, and accept any PRs that improve the current situation.

**Comment by UnsolvedCypher** [comment]
All I would ask is to change the font, which I believe can be done in the code snippet you linked to. I would be happy to submit a pull request, but it's probably best to have a few people agree on what the font should be before I go changing it. Or do people not care and any non-serif monospace font is fine?

**Comment by jfly** [comment]
If you can get it to be a sans-serif monospaced font, that would be a great start for discussion =)

**Comment by UnsolvedCypher** [comment]
Ok, I'll do a bit of research to make sure I'm choosing a universal font and I'll submit a pull request.

**Comment by lgarron** [comment]
For finding cross-platform fonts, search for "web-safe fonts".

**Comment by UnsolvedCypher** [comment]
It looks like you can embed a font into the jar
<http://stackoverflow.com/questions/11366354/itext-whats-going-on-with-font-basefont-and-createfont>
to definitely guarantee its availability. Should that be done to ensure
uniformity?

2015-04-20 22:07 GMT-04:00 Lucas Garron <notifications@github.com>:

**Comment by jfly** [comment]
I like the idea of embedding the font into the jar. How about you start with that and see if you can get things looking the same on my laptop as yours (I still have not installed ttf-ms-fonts)? You might find the tnoodle build process a little nasty. Do not hesitate to contact me via gchat if you have any questions (you should be able to find my gmail address through the git history).

**Comment by UnsolvedCypher** [comment]
I'm very sorry this has taken so long! I now have free time and am able to work on coding. I am not at home right now, but I will try to close this issue this week.

**Comment by StachuDotNet** [comment]
bump
