### ISSUE TITLE
Reduce pyraminx filtering to 6 moves.

### ISSUE THREAD

**Issue by lgarron** [cubing/tnoodle#193]
When/if [the new Regs fixes](https://github.com/cubing/wca-documents/pull/264) land.

**Comment by jfly** [comment]
The magic line of code is here: https://github.com/cubing/tnoodle/blob/master/scrambles/src/puzzle/PyraminxPuzzle.java#L37. Please submit a PR when this change is ready to go in.

**Comment by lgarron** [comment]
Will do.

**Comment by jfly** [comment]
Looks like this was fixed in #195. Closing this issue!
