### ISSUE TITLE
Capabilities to rename rounds

### ISSUE THREAD

**Issue by djoscarmix** [cubing/tnoodle#196]
Hi dear tnoodle team, Im Oscar Ceballos, Venezuelan Delegate. 
past weekend I had a 3 days competition and I generated each day the scrambles for the day. I realized that for each day the program generated a new Round 1 for the events, would be nice to recovery the capability to rename Rounds for the next version, this feature worked in past versions.

I had to edited it manually to upload the scrambles to Workbook assistant 

thank you so much in advance

**Comment by jfly** [comment]
You should not have to edit it manually to upload it to the workbook assistant. Are you familiar with the edit groups button in the workbook assistant? @Luis-J-Ianez has a great video on how to use this feature.

**Comment by djoscarmix** [comment]
Yes I saw the video.  But for example i added the three scramble files.
But it only had rounds 1.  Never find scramble for round 2 and 3. The Luis
video talk about Solving the issue for groups Not for rounds.

**Comment by jfly** [comment]
The workbook assistant definitely handles that case. I'm also pretty sure Luis's video talks about how to do this. I'm going to close this issue.
