### ISSUE TITLE
Change Square-1 and Megaminx colour schemes

### ISSUE THREAD

**Issue by Mollerz** [cubing/tnoodle#199]
This is not really a big issue but I thought I'd address it since it's crossed my mind a few times.

Currently the megaminx colour scheme is the mefferts colour scheme. I haven't seen this colour scheme in a competition for at least two years. I suggest changing it to the MF8 colour scheme which is becoming far more universal.

Square-1 is currently using the standard of White top, Green front. This is now an extremely uncommon colour scheme once again. All current square-1 cubes are sold with Yellow top, Red front. I think this would also make far more sense.

**Comment by jfly** [comment]
Thanks for making this issue. I'm all for making this change, it sounds totally reasonable. Are you comfortable submitting a pull request with the colors you like?

**Comment by Mollerz** [comment]
I have never used git outside of requesting issues before so I have no idea how to do that!

**Comment by jfly** [comment]
Here's the relevant code for Megaminx: https://github.com/cubing/tnoodle/blob/master/scrambles/src/puzzle/MegaminxPuzzle.java#L197-L212:

```java
    @Override
    public HashMap<String, Color> getDefaultColorScheme() {
        HashMap<String, Color> colors = new HashMap<String, Color>();
        colors.put("U", new Color(0xFFFFFF));
        colors.put("BL", new Color(0x882222));
        colors.put("BR", new Color(0x0000FF));
        colors.put("R", new Color(0x880088));
        colors.put("F", new Color(0x008800));
        colors.put("L", new Color(0x88DDFF));
        colors.put("D", new Color(0xFFFF00));
        colors.put("DR", new Color(0xFF0000));
        colors.put("DBR", new Color(0x000088));
        colors.put("B", new Color(0xFF44FF));
        colors.put("DBL", new Color(0x00FF00));
        colors.put("DL", new Color(0xFF8800));
        return colors;
    }
```

Here's the relevant code from SQ1: https://github.com/cubing/tnoodle/blob/master/scrambles/src/puzzle/SquareOnePuzzle.java#L52-L60

```java
    private static HashMap<String, Color> defaultColorScheme = new HashMap<String, Color>();
    static {
        defaultColorScheme.put("L", new Color(0xffff00));
        defaultColorScheme.put("B", new Color(0xff0000));
        defaultColorScheme.put("R", new Color(0x0000ff));
        defaultColorScheme.put("F", new Color(0xffc800));
        defaultColorScheme.put("U", new Color(0xffffff));
        defaultColorScheme.put("D", new Color(0x00ff00));
    }
```

GitHub does actually provide a little pencil for you to make changes wikipedia style online (just follow the links I sent you to find them) if you want to give it a shot and get your name in the TNoodle commit history. If you don't want to bother with that, I can totally make the change, can you tell me exactly what colors you think should be where, though?

**Comment by lgarron** [comment]
> the standard of White top, Green front

I think you mean white on top, green on bottom.

If we're switching to BOY, I suggest we go with white on top with green in front, to avoid going with an arbitrary yellow-red flavor-of-the-year color scheme. But switching to BOY sounds sensible.

**Comment by Mollerz** [comment]
Ah yes my mistake Lucas. However, again I think switching to White/Green as Top/Front is silly, because you just don't see that colour scheme. Every square-1 released since the mf8 V1 has come in the Yellow/Red as Top/Front scheme as default, that's over 5 years where all square-1s have been sold with this colour scheme, so I would hardly call it Flavour of the Year. And if the flavour does change in the next few years to something else (Which I don't see happening), then we can always apply the changes to TNoodle again.

jfly: I'll get on it now!

**Comment by lgarron** [comment]
If you're right and a large majority all Square-1s used in competitions are yellow-red, that sounds like a compelling reason.

A quick search turned up [Calvin's Square-1 on Amazon](http://www.amazon.com/Calvins-Puzzles-Square-Black-difficulty/dp/B009L8VUJW/ref=sr_1_10?ie=UTF8&qid=1451778438&sr=8-10&keywords=Square-1) with what appears to be yellow on bottom rather than top.

Would you mind doing a little research for a more citable reason that this change is a good idea?
If it's not easy to enumerate all Square-1s being sold, a poll on speedsolving.com about what Square-1 color schemes competitors have is probably easy, and a good way to confirm.

**Comment by Mollerz** [comment]
Personal experience from scrambling square-1 at every competition has led me to this conclusion. A vast majority are Yellow/Red, it is especially noticeable at major championships as well.

**Comment by lgarron** [comment]
> Personal experience from scrambling square-1 at every competition has led me to this conclusion.

Could you find some evidence to confirm that this is true around the world, too? (Maybe someone from Europe and someone from Asia.) I don't particularly doubt you, but so far this thread only has anecdotal evidence from your personal experience.

**Comment by Mollerz** [comment]
Just to update, I asked a Facebook Cubing Group that has a pretty international member base, and also some cube shop owners/workers. Yellow/Red is the most popular one people see for sure. Some solvers who use White/Red exclaimed that when they get a new square-1, they have to change the middle layer centre caps to obtain this colour scheme. The shop workers said all mf8, Calvins and QiYi square-1s come with Yellow/Red as default.

This is definitely enough evidence for me at least to go ahead with this scheme.

**Comment by lgarron** [comment]
> This is definitely enough evidence for me at least to go ahead with this scheme.

Alright, that sounds pretty compelling. Thanks for asking around.

**Comment by jfly** [comment]
Awesome! I am looking forward to the pull request!

**Comment by Mollerz** [comment]
Pull requests made, for square-1 I used the standard BOY colour scheme TNoodle uses. For megaminx I customised them to be as close to the mf8 scheme as possible. I used both a stickered dayan and tiled mf8 to work out closest colour.

**Comment by jfly** [comment]
Sweet! Are you able to run the code? Can you put screenshots on the PRs? If
not, I can do so.

**Comment by Mollerz** [comment]
I can't I'm afraid, so go ahead.

**Comment by jfly** [comment]
I've created a release with these changed here: https://github.com/cubing/tnoodle/releases/tag/v0.10.1. @Mollerz, let me know what you think. If this looks good, we can reach out to the Board and WRC and try to make version 0.10.1 official.

**Comment by Mollerz** [comment]
Looks good to me, it'll be interesting what the board say.

**Comment by jfly** [comment]
I believe this has been done now. Closing this issue.
