### ISSUE TITLE
Package naming in TNoodle-scrambles distribution

### ISSUE THREAD

**Issue by suushiemaniac** [cubing/tnoodle#202]
While the parent class "Puzzle" is referenced as
`net.gnehzr.tnoodle.scrambles.Puzzle`
all relevant subclasses are simply packaged as
`puzzle.XYZ` (with XYZ being `ThreeByThreeCubePuzzle` etc.)

This doesn't affect functionality but is certainly confusing/unconventional when using both of them in a single file, i. e.
`import net.gnehzr.tnoodle.scrambles.Puzzle;`
`import puzzle.MegaminxPuzzle;`

I suggest packaging all puzzle subclasses as `net.gnehzr.tnoodle.scrambles.XYZ` for consistency reasons.

**Comment by jfly** [comment]
I'm closing this, but am happy to accept a pull request that changes this.
