### ISSUE TITLE
Race condition with clock scrambles?

### ISSUE THREAD

**Issue by jfly** [cubing/tnoodle#206]
See while running `scrambles/src/net/gnehzr/tnoodle/test/ScrambleTest.java`:

```
Thread[Thread-23,5,main] 10 / 10
Testing clock
Generating a clock scramble
GOT LOCK Clock
Thread[Thread-23,5,main] 10 / 10
Drawing UR5- DR2+ DL4- UL5+ U4+ R5- D5- L3- ALL1- y2 U1- R2- D2- L0+ ALL2+ UR DL
Generating & drawing 2 sets of 10 scrambles simultaneously. This is meant to shake out threading problems in scramblers.
Thread[Thread-25,5,main] 1 / 10
SEVERE 35 1458499973475 net.gnehzr.tnoodle.scrambles.ScrambleCacher$2:uncaughtException  java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
	at java.util.LinkedList$ListItr.next(LinkedList.java:886)
	at net.gnehzr.tnoodle.scrambles.ScrambleCacher.fireScrambleCacheUpdated(ScrambleCacher.java:116)
	at net.gnehzr.tnoodle.scrambles.ScrambleCacher.access$600(ScrambleCacher.java:14)
	at net.gnehzr.tnoodle.scrambles.ScrambleCacher$1.run(ScrambleCacher.java:77)

Thread[Thread-26,5,main] 1 / 10
Thread[Thread-26,5,main] 1 / 10
Thread[Thread-26,5,main] 2 / 10
Thread[Thread-26,5,main] 2 / 10
Thread[Thread-26,5,main] 3 / 10
Thread[Thread-26,5,main] 3 / 10
Thread[Thread-26,5,main] 4 / 10
Thread[Thread-26,5,main] 4 / 10
Thread[Thread-26,5,main] 5 / 10
Thread[Thread-26,5,main] 5 / 10
Thread[Thread-26,5,main] 6 / 10
Thread[Thread-26,5,main] 6 / 10
Thread[Thread-26,5,main] 7 / 10
Thread[Thread-26,5,main] 7 / 10
Thread[Thread-26,5,main] 8 / 10
Thread[Thread-26,5,main] 8 / 10
Thread[Thread-26,5,main] 9 / 10
Thread[Thread-26,5,main] 9 / 10
Thread[Thread-26,5,main] 10 / 10
Thread[Thread-26,5,main] 10 / 10
```

**Comment by lgarron** [comment]
> Generating & drawing 2 sets of 10 scrambles simultaneously. This is meant to shake out threading problems in scramblers.

Just to make sure: Are you generating them simultaneously but putting them together in a predetermined order?

If you take them in the order they were generated, you may bias the start towards states that were (for whatever reason) easier to scramble. Probably not a concern for clock, but definitely for other puzzles.

**Comment by jfly** [comment]
That's a very interesting point, Lucas. Fortunately, our `ScrambleCacher` does [only generate one scramble at a time](https://github.com/cubing/tnoodle/blob/952eb7cc04994045e14bdad0e6a93f4a9c3df47e/scrambles/src/net/gnehzr/tnoodle/scrambles/ScrambleCacher.java#L50).

This test is special in that it creates 2 [`ScrambleCacher`'s at the same time](https://github.com/cubing/tnoodle/blob/952eb7cc04994045e14bdad0e6a93f4a9c3df47e/scrambles/src/net/gnehzr/tnoodle/test/ScrambleTest.java#L187-L188) and lets them run to completion. I believe the reason I added this test in the first placd is because we saw issues with generating PDFs while generating scrambles.
