### ISSUE TITLE
Change in FMC scrambles

### ISSUE THREAD

**Issue by andersonaap** [cubing/tnoodle#210]
[Question]

What is the reason for the 0.11.1 change in FMC scramble? 
https://www.worldcubeassociation.org/posts/tnoodle-0-11-1

Make solutions harder? Prevent cheating ...?

**Comment by pedrosino** [comment]
@andersonaap All FMC scrambles now start and end with the same combination of moves, which are not related to the scrambled state.
This is to prevent people accidentally (or intentionally) using the inverse scramble in their solution.

**Comment by jfly** [comment]
I'll see if we can make the internal discussion about how we decided upon this public. If there are no objections internally, I will make it public on May 1st.

**Comment by viroulep** [comment]
This changes occurred when clarifying this [incident](https://www.worldcubeassociation.org/forum/viewtopic.php?f=9&t=2020).
It goes with the following *upcoming* [Regulations changes](https://github.com/cubing/wca-regulations/pull/348/files).

**Comment by jfly** [comment]
Here are the key emails in the private discussion of how to do this. Hopefully they make sense.

Gritsenko:
> How about not a fixed length, but length that is definitely above God's 20?
This can be achieved by the following:
Generate a random state, apply 5 random moves, find a scramble for a new state, add those 5 inversed moves. If we get less than 25 moves due to some cancellation, but more than 19, it is still ok for us, because information "optimal solution is no more than X moves" is not leaked. If lots of moves were cancelled, and we got less than 20 moves, this seems to be unlucky and unlikely, and new 5 random moves should be generated.

Jeremy Fleischman:
> We could certainly do something like what Oleg suggests, but I suspect there's a cleaner implementation that involves changing Chen Shuang's two phase solver to keep searching for longer solutions. I dug into the min2phase code last night, and came up with a change that I believe works. Please see https://github.com/cubing/tnoodle/pull/203 for a detailed description. @Laura, despite being the creator of TNoodle, this stuff is very much not my area of expertise, and I'm going to need approval from someone I just cc-ed who truly groks this stuff before we can merge this up. 2 - 3 weeks might be tight for this.

Jeremy Fleischman:
> Oh right! I forgot that we can keep generating solutions. Unfortunately, I think this implementation might actually be more involved than Oleg's suggestion. Just to have names, I'm going to call this "Chen's suggestion". Here's my understanding of the various proposals, please correct me if I don't understand correctly:

> 1. Jeremy: Expand the phase2 solution to be long enough to bring our solution to exactly 25 moves. This seems to work well and fast, but it's unclear if it is actually possible for every cube state, and it could reveal useful information about how to orient edges (because the near optimal phase1 solution is unadultered).
> 2. Tom: Expand phase1 *and* phase2. Without some additional randomness, this means that the phase1 solutions will always start with the same turns, but is that actually a problem? Our choice of just where to put the padding (phase1 vs phase2) becomes somewhat arbitrary, and if we're not flexible, might make it impossible for us to find a solution??
> 3. Oleg: Pick a random state R, apply 5 moves (call it PAD_SUFFIX), find a scramble for that padded random state, call this S. Take that scramble S, and apply PAD_SUFFIX^-1 to get a (hopefully longer) scramble that will solve the original random state R. This could result in move cancellation, and so we'll have to keep picking PADs until there isn't much cancellation. It's not clear to me if this still has the same problem as Jeremy's in that it potentially reveals usable information.
> 4. Oleg #2 (aka: Sebastien's suggestion): Pick a random state R, but prefix it with PAD_PREFIX and suffix it with PAD_SUFFIX, find a scramble for this padded random state, call this S. PAD_PREFIX^-1 * S * PAD_SUFFIX^-1 will be a scramble for R. This will have an even higher probability of cancellations than Oleg's suggestion, but presumably has a lower probability of revealing useful information.
> 5. Chen: Just generate a random state and then apply 5 random moves. It's actually not totally clear to me that this preserves the uniformity of our scrambles. Furthermore, I believe this still reveals potentially useful phase1 stuff (?), and would require us to generate multiple solutions to the originally chosen random state until we find a solution that doesn't cancel with the 5 random moves we chose.
> 
> Of all of these, I actually believe #2 might be the simplest and best performant. I might take a dive into the 2phase solver again tomorrow to see if it's as simple as my original proposal was.

Jeremy Fleischman:
> For the record, I do not consider myself authorized to decide which of the possible implementations here is best. I do believe that the "exactly 25 moves" restriction should not influence our decision here, I think a 24-26 move scramble is fine (although it's still unclear to me if that's always even possible. Lucas says it's not proven possible, and I don't believe Tom has said one way or the other).
> 
> I looked into Tom's suggestion (#2 in my summary of methods, which is to expand both phase1 and phase2), and I really like it. I made a very simple change to pad phase2 to exactly minDepth / 2 = 25 / 2 = 12 (integer math, lol) moves, and I'm very pleased with the results (I've updated the PR here). Copy pasting the results here:
> 
> Generating scrambles with `startDepth1 = minDepth / 2 = 25 / 2 = 12` (note that the extra wiggle room on phase1 means that the solver seems to always get to start with its favorite first 2 turns: U R, which means that all the scrambles end with R' U')
> 
> ~/gitting/tnoodle @kaladin> TNOODLE_RANDSEED=1457343878214 ./tmt make run -p scrambles --args "333 333 333 333 333"
> ...
> Using TNOODLE_RANDSEED=1457343878214
> INFO 1 1457674856170 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 12 + phase2: 13 = U R U2 L' B' L F B' L' U' R2 B' .  L2 U2 B2 D B2 D2 R2 F2 D R2 U R2 U' (25f)
> U R2 U' R2 D' F2 R2 D2 B2 D' B2 U2 L2 B R2 U L B F' L' B L U2 R' U'
> INFO 1 1457674856723 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.552 seconds) 
> INFO 1 1457674856723 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 12 + phase2: 13 = U R U R' D' F B' D2 R' B U' F' .  U D2 L2 F2 B2 U L2 D2 R2 D' B2 D R2 (25f)
> R2 D' B2 D R2 D2 L2 U' B2 F2 L2 D2 U' F U B' R D2 B F' D R U' R' U'
> INFO 1 1457674856814 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.091 seconds) 
> INFO 1 1457674856814 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 12 + phase2: 13 = U R F2 R D' F2 U' D2 B2 R U' F .  U B2 U R2 B2 U D F2 L2 B2 L2 U' L2 (25f)
> L2 U L2 B2 L2 F2 D' U' B2 R2 U' B2 U' F' U R' B2 D2 U F2 D R' F2 R' U'
> INFO 1 1457674856860 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.046 seconds) 
> INFO 1 1457674856860 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 12 + phase2: 13 = U R F U2 B2 D' R' L2 B D2 L F' .  U B2 U' L2 D2 R2 D2 B2 D L2 F2 U F2 (25f)
> F2 U' F2 L2 D' B2 D2 R2 D2 L2 U B2 U' F L' D2 B' L2 R D B2 U2 F' R' U'
> INFO 1 1457674856876 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.016 seconds) 
> INFO 1 1457674856876 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 12 + phase2: 13 = U R U L2 D' L D L D B U F .  U R2 B2 D' B2 D2 F2 D' L2 U2 R2 B2 L2 (25f)
> L2 B2 R2 U2 L2 D F2 D2 B2 D B2 R2 U' F' U' B' D' L' D' L' D L2 U' R' U'
> INFO 1 1457674856890 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.014 seconds) 
> ~/gitting/tnoodle @kaladin> 
> 
> Generating scrambles with `startDepth1 = 0`:
> 
> ~/gitting/tnoodle @kaladin> TNOODLE_RANDSEED=1457343878214 ./tmt make run -p scrambles --args "333 333 333 333 333"
> ...
> Using TNOODLE_RANDSEED=1457343878214
> INFO 1 1457675026204 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 8 + phase2: 17 = F2 L' B2 L' F2 R' F2 U2 R2 F2 L' D2 F2 L R' F2 R' .  B' D' F' R' B D' U' R2 (25f)
> R2 U D B' R F D B R F2 R L' F2 D2 L F2 R2 U2 F2 R F2 L B2 L F2
> INFO 1 1457675026640 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.436 seconds) 
> INFO 1 1457675026640 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 8 + phase2: 17 = F2 R2 D B D2 F' L D .  F U2 F U2 F R2 B U2 L2 B R2 F' L2 F D2 F' L2 (25f)
> L2 F D2 F' L2 F R2 B' L2 U2 B' R2 F' U2 F' U2 F' D' L' F D2 B' D' R2 F2
> INFO 1 1457675026707 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.067 seconds) 
> INFO 1 1457675026707 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 9 + phase2: 16 = U' F L B R2 L' F' D L .  U R2 F2 U2 R2 U' F2 L2 U D2 F2 L2 U' L2 U' B2 (25f)
> B2 U L2 U L2 F2 D2 U' L2 F2 U R2 U2 F2 R2 U' L' D' F L R2 B' L' F' U
> INFO 1 1457675026744 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.037 seconds) 
> INFO 1 1457675026744 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 9 + phase2: 16 = L B L U D' R' B D L .  F U2 F' U2 F R2 B' R2 F U2 R2 B R2 U2 F' L2 (25f)
> L2 F U2 R2 B' R2 U2 F' R2 B R2 F' U2 F U2 F' L' D' B' R D U' L' B' L'
> INFO 1 1457675026773 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.028 seconds) 
> INFO 1 1457675026773 net.gnehzr.tnoodle.scrambles.Main:printScrambles STARTED Generating 333 scramble 
> Found! phase1: 10 + phase2: 15 = R2 L2 F R' D F B2 U B R .  U L2 D' F2 U' R2 F2 U2 R2 B2 U F2 R2 D B2 (25f)
> B2 D' R2 F2 U' B2 R2 U2 F2 R2 U F2 D L2 U' R' B' U' B2 F' D' R F' L2 R2
> INFO 1 1457675026792 net.gnehzr.tnoodle.scrambles.Main:printScrambles FINISHED Generating 333 scramble (took 0.019 seconds) 
> ~/gitting/tnoodle @kaladin> 
> 

Kit Clement:
> Something I really like about this fix is that the first two and last two moves appear to be fixed.  If so, then matching the scramble for 1-2 moves should actually be okay, as really those two moves are not informative of how to solve the scramble efficiently at all, knowing that they are in the scramble regardless of state.

Tom Rokicki:
> Interesting results!
> 
> If we're going this direction, and the exact length isn't critical, why not combine a bunch of the
> ideas we've seen so far into something this simple:
> 
> 1. Fix a set of prefix/suffix moves, say, U F R / U F R.
> 2. For a given position p, find *any* solution where that solution prefixed and suffixed with
>     the appropriate moves is canonical.
> 
> That's it.  So we generate a random position, then find any two-phase solution g such
> that U F R g U F R is a canonical sequence, and that's our FMC scramble.
> 
> The prefix/suffix will be easily recognizable and memorable and ideally finger-trick
> friendly (if it matters).
> 
> Someone wanting to practice speed FMC (hehe) can make up their own scrambles just
> by manually doing the prefix/suffix thing on any existing scrambler.
> 
> It does not perturb the uniformity of the random position selection.
> 
> It's simple enough that it is less likely to suffer from subtle defects due to the
> perturbation of the two-phase search (unlikely those these may be).
> 
> And even if the two-phase solution is short, adding U F R to the front and back makes it
> no longer be unusually short (with high probability).
> 

Jeremy Fleischman:
> I've implemented tom2 here: https://github.com/cubing/tnoodle/pull/205. The choice of prefix and suffix is easy to change, but right now it is R' F R. I'll leave this until next Wednesday to gather comments. If you really want to take a look but won't have a chance to look by Wednesday, let me know and I'll extend the deadline as needed.

Michael Young:
> I think that something more like R' U' F (some sequence that involves a quarter-turn on all three "axes") is better because it guarantees at least one bad edge in every orientation; with EO-first options becoming more popular, "guaranteeing" that solving EO optimally can't be derived from the scramble is a nice thing to have, I think.  (Someone who was both unscrupulous and lucky could see that R' F R doesn't affect U2/D2 EO, and therefore find out how to solve EO by looking at the solution ignoring the R' F R.  That being said, it still does change things, and I like how finger-tricky/reversible the current prefix is.)  Just my two cents, 'tho.


Jeremy Fleischman:
> R' U' F sounds reasonable to me. I've implemented that [here](https://github.com/jfly/tnoodle/commit/4e4916fb3e9f440f30df1a10781c224335bc2392).
